### ISSUE TITLE
Kangaroo_CPU.so: invalid ELF header

### ISSUE THREAD

**Issue by rusvo** [iceland2k14/kangaroo#14]
root@DESKTOP-OF08MGH:/home/rusvo/rsz# python3 kangaroo.py -p 03633CBE3EC02B9401C5EFFA144C5B4D22F87940259634858FC7E59B1C09937852 -ncore 2 -rand1
Traceback (most recent call last):
  File "/home/rusvo/rsz/kangaroo.py", line 58, in <module>
    ice = ctypes.CDLL(pathdll)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/rusvo/rsz/Kangaroo_CPU.so: invalid ELF header

hi, how to fix it?

**Comment by Mahuro** [comment]
It runs well in Ubnuntu22, maybe your OS needs updating / upgrading?
